version: '3.8'

services:
  app:
    build: .
    container_name: verityhub
    expose:
      - "${APP_PORT:-5000}"
    depends_on:
      - db
    environment:
      SERVICE_FQDN_VERITYHUB: ${SERVICE_FQDN_VERITYHUB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      SALT: ${SALT}
      TRANSFORMER_MODEL: ${TRANSFORMER_MODEL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_KEY: ${OPENAI_KEY}

  db:
    image: pgvector/pgvector:pg17
    container_name: db_container
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      SERVICE_FQDN_PGADMIN: ${SERVICE_FQDN_PGADMIN}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    expose:
      - 80
    depends_on:
      - db

volumes:
  postgres_data:
