services:
  app:
    image: yokowasis/verityhub:latest
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - db
    environment:
      SERVICE_FQDN_VERITYHUB:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      SALT: ${SALT}
      LLM_MODEL: ${LLM_MODEL}
      TRANSFORMER_MODEL: ${TRANSFORMER_MODEL}
    volumes:
      - uploads:/code/uploads

  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      SERVICE_FQDN_PGADMIN:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    expose:
      - 80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persist pgAdmin configurations and connections

volumes:
  postgres_data:
  pgadmin_data:
  uploads:
