services:
  app:
    build: .
    container_name: verityhub
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      - db
    environment:
      SERVICE_FQDN_VERITYHUB:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DATABASE:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-postgres}
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      SALT: ${SALT:-"$2b$12$7AeKxYspmpk8RZUIRk5NHu"}
      LLM_MODEL: ${LLM_MODEL:-"llama3.2:1b"}
      TRANSFORMER_MODEL: ${TRANSFORMER_MODEL:-"sentence-transformers/all-MiniLM-L6-v2"}
    volumes:
      - uploads:/code/uploads

  db:
    image: pgvector/pgvector:pg17
    container_name: db_container
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - ${POSTGRES_MAP_PORT:-5453}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      SERVICE_FQDN_PGADMIN:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    expose:
      - 80
    ports:
      - ${PGADMIN_MAP_PORT:-5050}:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persist pgAdmin configurations and connections

volumes:
  postgres_data:
  pgadmin_data:
  uploads:
